# Report for showing the averaged memory usage over this time period
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: knative-service-memory-usage
spec:
  reportingStart: '2019-06-01T00:00:00Z'
  reportingEnd: '2019-06-30T23:59:59Z'
  query: knative-service-memory-usage
  runImmediately: true
