apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  storage:
    type: "hive"
    hive:
      type: "s3"
      s3:
        # Manually created bucket
        bucket: "openshift-metering-storage"
        region: "us-west-1"
        # Secret can be created via oc create secret -n openshift-metering generic my-aws-secret --from-literal=aws-access-key-id=<my-key-id>  --from-literal=aws-secret-access-key=<my-key>
        secretName: "my-aws-secret"
        createBucket: false
  reporting-operator:
    spec:
      route:
        enabled: true
      authProxy:
        enabled: true
        htpasswdData: |
          kubeadmin:{SHA}PHZ8Qa+xKtoUAZDtgts/2TDi76M=
        cookieSeed: "UlHzGuwd0xScKlk0UTOvxJI7y0YxR8+2"
        subjectAccessReviewEnabled: true
        delegateURLsEnabled: true
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "150Mi"
          cpu: "100m"
  presto:
    spec:
      coordinator:
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
      worker:
        replicas: 0
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
  hive:
    spec:
      metastore:
        resources:
          requests:
            memory: "650Mi"
            cpu: "500m"
          limits:
            memory: "650Mi"
            cpu: "500m"
        storage:
          create: true
          size: "5Gi"
      server:
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "100m"